name: upper-build
on:
    push:
        paths:
            - 'upper/**'
            - '.github/workflows/upper-build.yaml'
    workflow_dispatch: #manual trigger
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v4
              with:
                go-version: '1.20'
            - run: go version